# Generated by Django 5.0.6 on 2024-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VapeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('flavors', models.JSONField()),
                ('url', models.URLField()),
            ],
        ),
    ]
